# Generated by Django 5.0 on 2024-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='true_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'user')},
        ),
    ]
