# Generated by Django 5.0 on 2024-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_user_name_user_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
