# Generated by Django 5.0 on 2024-01-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_order_address_order_name_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
